### ISSUE TITLE
Snake glitch w/ apples

### ISSUE THREAD

**Issue by jangomangodev** [sojs-coder/Multisnake#1]
After a while of playing Multisnake (very fun btw), I was encountering a couple of glitches. I ate my 2nd apple and immediately my snake grew 3x as big as it should have. Sometimes eating the apples didn't work. Now I am not sure what the cause of this glitch/bug is with the apples (or snake). If it is something that only happened to me I think it's nothing to worry about.

(bug

**Comment by sojs-coder** [comment]
hmmm. I have never heard of this happening before. I would assume that when you ate your second apple, an apple spawned right in front of you, and then one more spawned in front of that. The issue with the apples not doing anything is probably a client-side rendering bug. I will look into it. Thank you!
